"""add your_new_column

Revision ID: 37c80cee9cf3
Revises: 93b0ac5cc104
Create Date: 2025-07-02 19:55:03.026760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37c80cee9cf3'
down_revision: Union[str, None] = '93b0ac5cc104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tokens_id', table_name='tokens')
    op.drop_table('tokens')
    op.add_column('channels', sa.Column('access_token', sa.String(length=500), nullable=True))
    op.add_column('channels', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    op.add_column('channels', sa.Column('access_token_expiry', sa.BigInteger(), nullable=True))
    op.add_column('channels', sa.Column('refresh_token_expiry', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'refresh_token_expiry')
    op.drop_column('channels', 'access_token_expiry')
    op.drop_column('channels', 'refresh_token')
    op.drop_column('channels', 'access_token')
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('access_token_expiry', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_expiry', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel'], ['channels.channel_uid'], name='tokens_channel_fkey'),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey'),
    sa.UniqueConstraint('channel', name='tokens_channel_key')
    )
    op.create_index('ix_tokens_id', 'tokens', ['id'], unique=True)
    # ### end Alembic commands ###
